### ISSUE TITLE
Mechanism for Migrating QA Metrics to Final Metric Schema

### ISSUE THREAD

**Issue by philipbaileynar** [SouthForkResearch/CHaMP_Metrics#64]
We need a process for migrating metrics between two metric schemas. This could be any two schemas (e.g. topo, aux, topo+aux) but will typically be used for moving metrics from QA schemas to final schemas. The overall process will be:

1. Metrics calculated on AWS and transmitted back to cm.org via the API.
2. CHaMP Workbench  downloads the QA schemas using the new API download feature
3. Manual manipulation of metric values to fix problems (no tools scoped for budgeted for doing this. Has to be manual)
4. Copy Reviewed metrics to a new final metric schema. This "copy" doesn't exist yet, but would be really easy via the workbench.
5. Final metric schema uploaded to cm.org.

@MattReimer It's this last step that needs some thought... How can we populate a metric schema on cm.org with as few changes to our existing CHaMP Automation code as possible. Some thoughts:

What about exporting the final metric schema from the Workbench into the same XML format that the CHaMP Automation is expecting. These XML files could be placed on S3 at which point Lambda will detect them, see which final metric schema they are destined for and transmit them via the API.

## Questions

- What about logs/history/audit trail of the manual metric manipulation in step 3 above?

**Comment by MattReimer** [comment]
@philipbaileynar I really don't like the XML intermediary step. It creates a no-man's-land where we're not sure what's going on. I think the best way to go here is to teach the workbench to:

1. Create final schemas in the API if they don't exist
2. Push data from QA schemas to final schemas
3. Handle collisions when final Schemas already exist.

We talked about having final schemas be "snapshots" of the data so instead of handling collisions on a per-instance basis I think we can safely just blow away the whole schema and re-create it. 

We should probably teach the workbench to back up a schema to a big XML or JSON or something so we can put it all back if we delete the wrong one by accident. 

Overall I don't think this would be too much work and there is nothing here we haven't already done in the NodeJS automation so you can probably just steal the methodology straight from there.

**Comment by philipbaileynar** [comment]
@MattReimer I'm on-board with your suggestion. Let's whiteboard the workflow so that I can build in the error handling and correct steps from the beginning.

**Comment by MattReimer** [comment]
cool

**Comment by volkcj** [comment]
minor comment on requirements--

- final schemas need to become 'public' in cm.org, so they need to populate the 'published' tag affiliated with a schema.
- will require metric membership in multiple schemas in WB (unsure of status of this issue in wb)
- can this process also be evaluated for tying in to Riverscapes projects?  My initial scoping of a champ metric Riverscapes project ("sites to network") would use metric schemas as either an input to Riverscapes, or as a Realization/Analysis output.

**Comment by philipbaileynar** [comment]
@volkcj see below:

* Yes, we know the final schemas need to be public. 
* I have restructured the way model runs and metrics are stored in the Workbench. This supports:
    * Each metric schema belongs to a program.
    * Each metric schema has metric definitions associated with it.
    * Each metric definition can belong to multiple metric schemas.
* Yes, the sites on network project would draw from one or more metric schemas

**Comment by philipbaileynar** [comment]
I just mocked up the user interface for this. Appreciate feedback.

https://youtu.be/_Xsz9toubY8

**Comment by philipbaileynar** [comment]
This is implemented. Will be in the next version of workbench.
