### ISSUE TITLE
Topo: Wetted and Bankfull xsection metrics reporting same values

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#80]
BfWdth_Avg and WetWdth_Avg
BfWdth_CV and WetWdth_CV
BfWDRat_Avg and WetWDRat_Avg
BfWDRat_CV and WetWDRat_CV

BFSCWDRat_Avg and WetSCWDRat_Avg
BFSCWDRat_CV and WetSCWDRat_CV
BFSCWMaxDRat_CV and WetSCWMaxDRat_CV
BFSCWMaxDRat_Avg and WetSCWMaxDRat_Avg
BFSCWdth and WetSCWdth
BFSCWdth_CV and WetSCWidth_CV

**Comment by philipbaileynar** [comment]
At the very least, there is a metric definition inconsistency. Bankfull is using the **main** channel while the wetted metric uses **channel**:

Metric ID | Name | Xpath
-- | -- | --
139 | BfWdth_Avg | Bankfull/CrossSections/Main/Best/WetWidth/Mean
157 | WetWdth_Avg | Wetted/CrossSections/Channel/Best/WetWidth/Mean

**Comment by MattReimer** [comment]
The fix here was due to a template array that was supposed to make a deep copy but was only making a shallow copy. As a result the Wetted channel metrics got repopulated with Bankfull metrics. 

I can confirm this only affected Cross sections since they were the only ones deep enough to need a deep copy

**Comment by volkcj** [comment]
resolved.
