### ISSUE TITLE
Topo Tier 2 metrics do not show in workbench

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#89]
When QA - Topo Tier 2 Metrics is selected from Workbench the grid is empty.  No error thrown, but also no metrics...

**Comment by volkcj** [comment]
7.0.21 still has this issue.

**Comment by philipbaileynar** [comment]
This was fixed with 4eb1e7e9d6c01aec9bd0cbdac3a1316e4c48db74. The tier name was being omitted from the topo metric output template when an occurence of a particular channel unit type was not present. This would then output a topo metric XML with `0` for the metric name. The workbench would then choke because it couldn't find this channel unit type in it's lookup dictionary.

**Comment by volkcj** [comment]
resolved. closing.
